Repository MyMealCalorie/client, pull requests merged in 2022-08, with the labels that each got.

#2 feat: 페이지 라우팅 구현
  src/App.tsx
  src/index.tsx
  src/pages/Analysis/index.tsx
  src/pages/LogIn/index.tsx
  src/pages/LogOut/index.tsx
  src/pages/Main/index.tsx
Labels: feat

#4 feat: login 페이지 구현
  package-lock.json
  package.json
  src/components/Login/Footer.tsx
  src/components/Login/LoginForm.tsx
  src/components/Login/Logo.tsx
  src/components/common/CenterBox.tsx
  src/hooks/useInput.ts
  src/index.css
  src/index.tsx
  src/pages/LogIn/index.tsx
  src/style/Button.style.ts
  src/style/CenterLayout.style.ts
  src/style/FlexBox.style.ts
Labels: feat

#7 [STYLE] main 페이지 레이아웃 구현
  .idea/.gitignore
  .idea/MyMealCalorie.iml
  .idea/codeStyles/codeStyleConfig.xml
  .idea/modules.xml
  .idea/vcs.xml
  src/components/Main/Calendar.tsx
  src/components/Main/Chart.tsx
  src/components/Main/SelectedDate.tsx
  src/components/Main/Today.tsx
  src/components/common/Header.tsx
  src/pages/Main/index.tsx
  src/style/Footer.style.ts
Labels: style

#9 [STYLE]: styled-components naming convention 적용 및 props 변경
  src/components/Login/Footer.tsx
  src/components/Login/LoginForm.tsx
  src/components/common/CenterBox.tsx
  src/pages/LogIn/index.tsx
  src/style/Button.style.ts
  src/style/CenterBox.style.tsx
  src/style/CenterLayout.style.ts
  src/style/FlexBox.style.ts
Labels: style

#10 [STYLE] user/signup 페이지 레이아웃 구현
  src/App.tsx
  src/components/Login/LoginForm.tsx
  src/components/SignUp/SignUpForm.tsx
  src/components/SignUp/Title.tsx
  src/components/common/Header.tsx
  src/pages/LogOut/index.tsx
  src/pages/Main/index.tsx
  src/pages/SignUp/index.tsx
Labels: style

#11 [STYLE] 하루데이터 리스트 UI 구현
  src/components/Main/OneDayList.tsx
  src/components/Main/SelectedDate.tsx
  src/components/common/OneMeal.tsx
  src/pages/Main/index.tsx
Labels: style

#16 [STYLE/CHORE] 식사데이터 디테일 모달창 추가, OneMeal props 타입 변경
  src/components/Main/OneDayList.tsx
  src/components/common/OneMeal.tsx
  src/components/common/OneMealDetailModal.tsx
Labels: style, chore

#17 [STYLE/REFACTOR] 식사데이터 모달창 구현, 하루데이터 리스트 컴포넌트 분리
  src/components/Main/OneDayListContainer.tsx
  src/components/common/OneDayList.tsx
  src/components/common/OneMeal.tsx
  src/components/common/OneMealDetailModal.tsx
  src/pages/Main/index.tsx
Labels: style, refactor

#19 [STYLE] Additional-Information-Modal UI 구현
  src/components/Main/AdditionalInformationModal.tsx
Labels: style

#20 [style] TodayNutrition UI 구현
  src/components/Main/Today.tsx
  src/components/Main/TodayNutrition.tsx
  src/pages/Main/index.tsx
Labels: style

#22 [STYLE] react-calendar 적용
  package-lock.json
  package.json
  src/components/Main/Calendar.tsx
  src/components/Main/CalendarContainer.tsx
  src/components/Main/OneDayListContainer.tsx
  src/components/common/OneDayList.tsx
  src/pages/Main/index.tsx
Labels: style

#24 [FEAT/STYLE] image upload modal 구현
  src/components/Main/ImgUploadModal.tsx
  src/components/Main/TodayNutrition.tsx
Labels: feat, style

#29 [STYLE] weekly-calorie-chart UI 구현
  package-lock.json
  package.json
  src/components/Main/Chart.tsx
  src/components/Main/TodayNutrition.tsx
  src/components/Main/WeeklyCalorieChart.tsx
  src/pages/Main/index.tsx
Labels: style

#31 [STYLE] Analysis 페이지 UI 구현
  src/pages/Analysis/index.tsx
  src/pages/Analysis/style.ts
  src/pages/Main/index.tsx
  src/pages/Main/style.ts
  src/style/FlexBox.style.ts
Labels: style

#36 Feat/index page
  public/carrots.jpg
  src/App.tsx
  src/components/Home/Main.tsx
  src/components/Home/style/index.ts
  src/pages/Home/index.tsx
  src/pages/Home/style.ts
Labels: feat, style

#39 [ FEAT] sign up
  package-lock.json
  package.json
  src/actions/signUpAction.ts
  src/components/SignUp/SignUpForm.tsx
  src/pages/SignUp/index.tsx
  src/slices/userSlice.ts
  src/store/store.ts
  src/utils/domain.ts
  src/utils/regExp.ts
Labels: feat, refactor

#41 [FEAT] user login 로직 구현
  src/actions/logInAction.ts
  src/actions/signUpAction.ts
  src/components/Login/LoginForm.tsx
  src/components/SignUp/SignUpForm.tsx
  src/slices/userSlice.ts
Labels: feat, refactor

#43 [STYLE] 전체 디자인 수정
  src/components/Main/CalendarContainer.tsx
  src/components/Main/ImgUploadModal.tsx
  src/components/Main/OneDayListContainer.tsx
  src/components/Main/TodayNutrition.tsx
  src/components/Main/WeeklyCalorieChart.tsx
  src/components/Main/style/calendar.css
  src/components/Main/style/index.ts
  src/components/common/OneDayList.tsx
  src/components/common/OneMeal.tsx
  src/components/common/OneMealDetailModal.tsx
  src/components/common/style/index.ts
  src/pages/Analysis/index.tsx
  src/pages/Analysis/style.ts
  src/pages/LogIn/index.tsx
  src/pages/Main/index.tsx
  src/pages/Main/style.ts
  src/style/CenterBox.style.tsx
  src/style/CenterLayout.style.ts
  src/style/FlexBox.style.ts
  src/style/Footer.style.ts
Labels: style

#44 [STYLE] login signup design
  src/assets/carrots.jpg
  src/assets/kakao_login.png
  src/components/Login/LoginForm.tsx
  src/components/Login/Logo.tsx
  src/components/Login/style/index.ts
  src/components/SignUp/SignUpForm.tsx
  src/components/SignUp/style/index.ts
  src/pages/Home/index.tsx
  src/pages/LogIn/index.tsx
  src/pages/SignUp/index.tsx
  src/style/CenterBox.style.tsx
  src/types/images.d.ts
  tsconfig.json
Labels: style, fix

#46 feat: 404 page route 추가
  src/App.tsx
  src/pages/NotFound/index.tsx
  src/pages/NotFound/style.ts
Labels: feat

#48 [STYLE] 메인 로고, favicon 삽입
  public/favicon.ico
  public/index.html
  src/assets/main_logo.png
  src/components/Login/Logo.tsx
  src/components/Login/style/index.ts
  src/components/common/Header.tsx
  src/components/common/style/index.ts
  src/pages/LogIn/index.tsx
  src/utils/color.ts
Labels: style

#49 [STYLE] index 페이지 design
  src/assets/apples.jpg
  src/assets/carrots.jpg
  src/components/Home/Main.tsx
  src/components/Home/style/index.ts
  src/pages/Home/index.tsx
Labels: style

#52 [FEAT] login auth
  src/actions/logInAction.ts
  src/actions/signUpAction.ts
  src/components/Login/LoginForm.tsx
  src/components/SignUp/SignUpForm.tsx
  src/pages/Main/index.tsx
  src/utils/auth.tsx
Labels: feat, fix

#54 [STYLE] 이미지 분석 페이지 확인 안내 말풍선 UI
  src/pages/Analysis/index.tsx
  src/pages/Analysis/style.ts
Labels: style

#57 [CHORE] 리덕스 폴더 응집
  src/_actions/logInAction.ts
  src/_actions/signUpAction.ts
  src/_slices/userSlice.ts
  src/_store/hooks.ts
  src/_store/store.ts
  src/components/Login/LoginForm.tsx
  src/components/SignUp/SignUpForm.tsx
  src/index.tsx
Labels: chore

#58 [STYLE] index 배경 이미지 변경
  src/assets/apples.jpg
  src/assets/bananas.jpg
  src/components/Home/style/index.ts
  src/pages/Home/index.tsx
Labels: style

#59 [FEAT] header route
  package-lock.json
  package.json
  src/components/Home/Main.tsx
  src/components/common/Header.tsx
  src/components/common/style/index.ts
Labels: feat, style

#60 style: 이미지 업로드 모달 크기 조정
  src/components/Main/ImgUploadModal.tsx
  src/components/Main/style/index.ts
Labels: style

#61 [STYLE] home 페이지 중앙 버튼 디자인 변경
  src/components/Home/style/index.ts
  src/components/common/Header.tsx
  src/utils/color.ts
Labels: style

#62 [REFACTOR] 선택한 날짜 데이터 리덕스로 상태관리
  src/_slices/dateSlice.ts
  src/_store/store.ts
  src/components/Main/CalendarContainer.tsx
  src/pages/Main/index.tsx
Labels: refactor

#63 [FIX] 선택 날짜 데이터 각 컴포넌트에서 받아오도록 수정
  src/components/Main/CalendarContainer.tsx
  src/components/Main/OneDayListContainer.tsx
  src/pages/Main/index.tsx
Labels: fix

#66 [STYLE] 반응형 디자인 적용 및 디자인 디테일 수정
  src/components/Home/style/index.ts
  src/components/Main/AdditionalInformationModal.tsx
  src/components/Main/ImgUploadModal.tsx
  src/components/Main/style/index.ts
  src/components/common/OneMealDetailModal.tsx
  src/components/common/style/index.ts
  src/pages/Analysis/index.tsx
  src/pages/Analysis/style.ts
  src/pages/Main/style.ts
  src/utils/color.ts
Labels: style

#68 [CHORE] alert멘트, atuh추가, title 변경
  src/components/Login/LoginForm.tsx
  src/components/Main/TodayNutrition.tsx
  src/components/SignUp/SignUpForm.tsx
  src/pages/Analysis/index.tsx
Labels: chore

#69 style: CenterBox, 모달 버튼 반응형 추가, 문자 간격추가
  src/components/Main/style/index.ts
  src/style/CenterBox.style.tsx
Labels: style

#70 [CHORE] 환경변수 설정
  .gitignore
  package-lock.json
  src/_actions/logInAction.ts
  src/_actions/signUpAction.ts
  src/_store/store.ts
  src/utils/domain.ts
Labels: chore

#71 [STYLE] 달력 디자인 수정
  .env
  src/components/Main/style/calendar.css
Labels: style

#72 [STYLE] Chart UI 변경
  .gitignore
  src/components/Main/WeeklyCalorieChart.tsx
  src/components/Main/style/index.ts
Labels: style

#74 [FEAT] 이미지 분석 결과 보여주기
  src/components/Analysis/AnalyzedImg/index.tsx
  src/components/Analysis/AnalyzedImg/style.ts
  src/components/Analysis/DetailSheet/index.tsx
  src/components/Analysis/DetailSheet/style.ts
  src/pages/Analysis/index.tsx
Labels: feat, style, refactor
